### ISSUE TITLE
Changing files..

### ISSUE THREAD

**Issue by t-e-s-tweb** [z4x7k/sing-box-all#1]
Hey how would I got about modifying this build config so that during building I insert random text into the line singbox a client for proxying so that the md5 of the final file changes during each build?

**Comment by z4x7k** [comment]
Sorry, @t-e-s-tweb. I could not clearly understand your desired goal. Can you provide an example of what your trying to achieve?

> so that the md5 of the final file changes during each build?

Also, any changes in the source files, either changing an existing file's content, or adding, or removing a file will result in a different checksum.
